name = "aiken-lang/cardano-verify"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/cardano-verify'"

[repository]
user = "aiken-lang"
project = "cardano-verify"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"
